"""add index knowledge_bases user_id

Revision ID: 8221d72232e5
Revises: a910dab74e9f
Create Date: 2026-07-21 20:37:22.558843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8221d72232e5'
down_revision: Union[str, Sequence[str], None] = 'a910dab74e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_knowledge_bases_user_id', 'knowledge_bases', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_bases_user_id', table_name='knowledge_bases')
    # ### end Alembic commands ###
